### ISSUE TITLE
[Webinars] List Past Webinar Files

### ISSUE THREAD

**Issue by kyleboe** [kyleboe/zoom_rb#333]
https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/listpastwebinarfiles

**Comment by joelmichael** [comment]
This link seems incorrect as it just goes to what appears to be a bunch of binary data printed as text in my browser.

**Comment by kyleboe** [comment]
Oh wild. Yeah they have revamped their API docs since these were created. I don't see an immediate replacement so I'm fine with just closing it out.
