### ISSUE TITLE
Zoom::ParameterMissing ([:access_token]):

### ISSUE THREAD

**Issue by mkenny** [kyleboe/zoom_rb#384]
I've set up a user managed OAuth app on Zoom marketplace and from that I have my installation url 

[https://zoom.us/oauth/authorize?response_type=code&client_id=xxx&redirect_uri=yyy](https://zoom.us/oauth/authorize?response_type=code&client_id=xxx&redirect_uri=yyy)

In my redirect controller I have the following : 
```
require 'zoom'

class Services::ApiServicesController < ApplicationController
  def new
    auth = Zoom::Client::OAuth.new(auth_code: params[:code], redirect_uri: 'yyy', timeout: 15).auth
    zoom_client = Zoom::Client::OAuth.new(access_token: auth['access_token'], timeout: 15)
  end
end
```
When this runs I get the following error:
```
Zoom::ParameterMissing ([:access_token]):
```

It was my understanding that `Zoom::Client::OAuth.new(auth_code: params[:code], redirect_uri: 'yyy', timeout: 15).auth` would generate the access_token

Any ideas would be really appreaciated

**Comment by kyleboe** [comment]
Hmmmm yeah everything looks correct. I'm curious what version you are running and what `auth` looks like when `'access_token'` is trying to be read. Would you mind posting that info so we can debug futher?

**Comment by dil-bparihar** [comment]
Is this issue is being resolved....because i am also getting the same error @kyleboe

**Comment by kyleboe** [comment]
Interesting. I'm curious if you can post some of the debugging steps requested above to provide some additional context. I'm not sure how to start debugging otherwise.
