### ISSUE TITLE
Support for Server 2 Server OAuth

### ISSUE THREAD

**Issue by mauntrelio** [kyleboe/zoom_rb#453]
The JWT app type will be deprecated in June, 2023. Is there a plan to support Server 2 Server OAuth?

**Comment by kyleboe** [comment]
Ah. Yeah we should be able to add that support. I just checked out the docs and it doesn't seem too crazy to add. 

https://developers.zoom.us/docs/internal-apps/s2s-oauth/

**Comment by kyleboe** [comment]
Actually, I just realized we already have support for S2SOAuth here: https://github.com/kyleboe/zoom_rb/blob/main/lib/zoom/clients/server_to_server_oauth.rb

Shout out to @Tekkon for adding that!
